site_name: Ayuda de El Prado

theme:
  name: mkdocs
  language: es

nav:
  - Inicio: index.md
  - Pantallas:
      - Consulta de notificaciones: pantallas/TFormConsultaNotificaciones.md
      - Análisis de campañas: pantallas/TFormCampaniasAnalisis.md
